#!/bin/bash
# 
# 2008      Nico Schottelius (nico-ceofhack at schottelius.org)
# 
# This file is part of ceofhack.
#
# ceofhack is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# ceofhack is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with ceofhack. If not, see <http://www.gnu.org/licenses/>.
#
# Implement a tcp4 listener
#
# NOTE: Currently broken. Use C listener instead.

#
# return codes:
# 1: wrong number of arguments (must be one)
# 2: unsupported protocol
#

if [ "$#" -ne 1 ]; then
   exit 1
fi

fulladdr="$1"
# address without protocol
addr="$(echo $fulladdr | awk -F: '/^tcp:/ { print $2 }')"
port="$(echo $fulladdr | awk -F: '/^tcp:/ { print $3 }')"

[ "$port" ] || port=4242

echo Listening on: ${addr}:$port 1>&2
nc -l -p "$port"
