DESTDIR=

LDFLAGS=$(shell gpgme-config --libs)
CFLAGS=-Wall -Wextra -Wno-unused-parameter -Werror -pipe -g -D_FILE_OFFSET_BITS=64 -I.
CFLAGS+=$(shell gpgme-config --cflags)


CC=gcc $(CFLAGS)
LD=gcc $(LDFLAGS)

EOFs=tp ui_cmd
