#!/bin/sh
# 
# 2008      Nico Schottelius (nico-ceofhack at schottelius.org)
# 
# This file is part of ceofhack.
#
# ceofhack is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# ceofhack is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with ceofhack. If not, see <http://www.gnu.org/licenses/>.
#
# Implement a tcp4 listener
#

#
# codes: see EOF.tex
#

while : ; do
   read command

   case "$command" in
      1000)
         echo -n 2001
         ;;
   esac
done

exit

fulladdr="$1"
# address without protocol
addr="$(echo $fulladdr | awk -F: '/^tcp:/ { print $2 }')"
port="$(echo $fulladdr | awk -F: '/^tcp:/ { print $3 }')"

# debug on stderr
echo Connecting to $fulladdr 1>&2

nc "$addr" "$port"
