#!/bin/bash
# 
# 2008      Nico Schottelius (nico-ceofhack at schottelius.org)
# 
# This file is part of ceofhack.
#
# ceofhack is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# ceofhack is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with ceofhack. If not, see <http://www.gnu.org/licenses/>.
#
# Implement a tcp4 listener
#

#
# codes: see EOF.tex
#

read -n 5 command

if [ "$command" != "1000" ]; then
	echo "Unknown command." 1>&2
	echo -n 2001
	exit 1
fi

fulladdr="$1"
# address without protocol://
addr="$(echo $fulladdr | awk -F: '/^tcp:\/\// { print substr($2,3) }')"
port="$(echo $fulladdr | awk -F: '/^tcp:\/\// { print $3 }')"

if [ -z "$addr" -o -z "$port" ]; then
	echo "Invalid protocol or no address or no port." 1>&2
	exit 1
fi

# debug on stderr
echo "Connecting to $fulladdr" 1>&2

if nc -q 0 "$addr" "$port" > /dev/null; then
	echo -n 2000
	exit 0
else
	echo -n 2001
	exit 1
fi

