--- !ditz.rubyforge.org,2008-03-06/project 
name: ceofhack
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: ceofhack
- !ditz.rubyforge.org,2008-03-06/component 
  name: ceof
- !ditz.rubyforge.org,2008-03-06/component 
  name: tp
- !ditz.rubyforge.org,2008-03-06/component 
  name: doc
- !ditz.rubyforge.org,2008-03-06/component 
  name: postbote
- !ditz.rubyforge.org,2008-03-06/component 
  name: ui
- !ditz.rubyforge.org,2008-03-06/component 
  name: crypto
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "1.0"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-04-07 21:38:44.208681 Z
    - Nico Schottelius <nico@ikn.schottelius.org>
    - created
    - The first usable release of EOF-2
- !ditz.rubyforge.org,2008-03-06/release 
  name: "1.1"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-04-10 11:27:17.751007 Z
    - Nico Schottelius <nico@ikn.schottelius.org>
    - created
    - |-
      Cleanup of 1.0, which allows others to contribute to EOF-2:
      
      * Create sample transport protocols
      * handling all commands
      * implementation at least in C
      * sample implementation in other languages (perl, python, ruby) would be helpful
      * Add user interface
      * So other UIs can be created
      * Cleanup ui_cmd, so it can be used as a reference
      * Fix bugs of 1.0 ;-)
- !ditz.rubyforge.org,2008-03-06/release 
  name: "1.2"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-04-17 07:58:33.590637 Z
    - Nico Schottelius <nico@ikn.schottelius.org>
    - created
    - This release will contain new features after the bugfix release 1.1.
