--- !ditz.rubyforge.org,2008-03-06/project 
name: ceofhack
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: ceofhack
- !ditz.rubyforge.org,2008-03-06/component 
  name: ceof
- !ditz.rubyforge.org,2008-03-06/component 
  name: tp
- !ditz.rubyforge.org,2008-03-06/component 
  name: doc
- !ditz.rubyforge.org,2008-03-06/component 
  name: postbote
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "1.0"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-04-07 21:38:44.208681 Z
    - Nico Schottelius <nico@ikn.schottelius.org>
    - created
    - The first usable release of EOF-2
